### ISSUE TITLE
[social_structure population mean_shortest_path_length] RuntimeError: Execution stopped: (0<=ValN)&&(ValN<Vals)...

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#10]
SOCIALSIM MEASUREMENTS | Running social_structure population mean_shortest_path_length... 
--------------------------------------------------------------------------------
> Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/measurements.py", line 130, in _evaluate_measurement
    result = function(**function_arguments)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/social_structure.py", line 45, in mean_shortest_path_length
    return sn.GetBfsEffDiam(self.gUNsn, 500, False)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/snap.py", line 302854, in GetBfsEffDiam
    if type(tspec) == PUNGraph: return GetBfsEffDiam_PUNGraph(tspec, *args)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/snap.py", line 289164, in GetBfsEffDiam_PUNGraph
    return _snap.GetBfsEffDiam_PUNGraph(*args)
RuntimeError: Execution stopped: (0<=ValN)&&(ValN<Vals) [Reason:'Index:-1 Vals:0 MxVals:0 Type:4TVecI7TKeyDatI6TInt644TFltExE'], file ../../snap-dev-64/glib-core/ds.h, line 527

**Comment by emily-grace** [comment]
This was an issue with empty graphs in the network measurements.  We've updated the error handling to provide a warning for this.
