### ISSUE TITLE
[social_structure population max_node_degree] ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#11]
SOCIALSIM MEASUREMENTS | Running social_structure population max_node_degree... 
--------------------------------------------------------------------------------
> Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/measurements.py", line 130, in _evaluate_measurement
    result = function(**function_arguments)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/social_structure.py", line 66, in max_node_degree
    return max(ig.Graph.degree(self.gUNig))
ValueError: max() arg is an empty sequence

**Comment by emily-grace** [comment]
This was an issue with empty graphs in the network measurements.  We've updated the error handling to provide a warning for this.
