### ISSUE TITLE
[social_structure population mean_node_degree] ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#12]
SOCIALSIM MEASUREMENTS | Running social_structure population mean_node_degree... 
--------------------------------------------------------------------------------
> Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/measurements.py", line 130, in _evaluate_measurement
    result = function(**function_arguments)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/social_structure.py", line 69, in mean_node_degree
    return 2.0*ig.Graph.ecount(self.gUNig)/ig.Graph.vcount(self.gUNig)
ZeroDivisionError: float division by zero

**Comment by emily-grace** [comment]
This was an issue with empty graphs in the network measurements.  We've updated the error handling to provide a warning for this.
