### ISSUE TITLE
ValueError: No objects to concatenate in measurements/cross_platform.py, line 567

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#3]
> SOCIALSIM MEASUREMENTS | Running cross_platform population temporal_correlation_share... 
--------------------------------------------------------------------------------
> Traceback (most recent call last):
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/measurements.py", line 130, in _evaluate_measurement
    result = function(**function_arguments)
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/cross_platform.py", line 567, in temporal_correlation
    data = pd.concat(dfs)
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by emily-grace** [comment]
Does the input data you are using include more than one platform?

**Comment by mbamba** [comment]
No, just reddit. 
The scripts should be able to detect and skip the measurements that cannot be evaluated without throwing an exception.

**Comment by emily-grace** [comment]
We've added a check for more than one platform in each cross platform measurement.  Now it will give a warning and return None if only one platform is present.

In any case, the package will fill the measurement with a None value if it throws an exception during execution so the end result is the same, but hopefully the cause of the issue will be more transparent now.
