### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'socialsim/measurements/model_parameters/best_model.pkl'

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#4]
The following exception is triggered due to a hardcoded path in metadata.py line 65. The file exists but the script is not given the parent location.

> Traceback (most recent call last):
  File "task_runner.py", line 16, in <module>
    metadata = ss.MetaData(community_directory='data/communities/')
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/metadata.py", line 65, in __init__
    self.estimator = joblib.load(model_dir)
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 590, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'socialsim/measurements/model_parameters/best_model.pkl'

**Comment by emily-grace** [comment]
Changed this to a relative file path
