### ISSUE TITLE
KeyError: 'community' originating from multi-platform.py

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#6]
The following is triggered 30 times by multi-platform.py failing to process events simulated on a single platform (not multiple).

SOCIALSIM MEASUREMENTS | Running multi_platform community ... 
--------------------------------------------------------------------------------
> Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/measurements.py", line 130, in _evaluate_measurement
    result = function(**function_arguments)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/multi_platform.py", line 664, in lifetime_of_info
    node_level=node_level)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/multi_platform.py", line 196, in scalar_measurement
    result = data.groupby(group_cols)[agg_col].apply(agg_func)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/generic.py", line 7632, in groupby
    observed=observed, **kwargs)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2110, in groupby
    return klass(obj, by, **kwds)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 360, in __init__
    mutated=self.mutated)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/groupby/grouper.py", line 578, in _get_grouper
    raise KeyError(gpr)
KeyError: 'community'

Instead of an exception, there could be a warning like the following:

> /anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/cross_platform.py:320: UserWarning: Not enough platforms for cross-platform measurements
  warnings.warn("Not enough platforms for cross-platform measurements")

**Comment by emily-grace** [comment]
Multi-platform can be run on a single platform (unlike cross platform) which requires multiple.  This was caused by no valid communities being found in the data.  We updated the error handling to provide a more useful warning for this.
