### ISSUE TITLE
[persistent_groups meas.] TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#8]
> --------------------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/run.py", line 175, in run_measurements
    configuration_subset, metadata)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/persistent_groups.py", line 52, in __init__
    self.get_network_from_bursts()
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/persistent_groups.py", line 85, in get_network_from_bursts
    burst_intervals = burstDetection.detect_bursts()
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/recurrence.py", line 79, in detect_bursts
    bursts_df = self.detect_bursts_of_a_timeseries(counts_df, gamma=gamma)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/recurrence.py", line 105, in detect_bursts_of_a_timeseries
    gamma = self.predict_gamma_for_timeseries(timeseries_df)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/recurrence.py", line 129, in predict_gamma_for_timeseries
    disable_progressbar=True)[selected_features].fillna(0)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 159, in extract_features
    distributor=distributor)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 296, in _do_extraction
    function_kwargs=kwargs)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 149, in map_reduce
    result = list(itertools.chain.from_iterable(result))
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1002, in __iter__
    for obj in iterable:
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

**Comment by emily-grace** [comment]
I was not able to replicate this issue. Let me know if you are still experiencing it after the recent update.  It's possible than an earlier issue that I fixed also resolved this one.
