### ISSUE TITLE
[utils.py] ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#9]
> --------------------------------------------------------------------------------
SOCIALSIM TASKRUNNER   | Subsetting twitter data... 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/run.py", line 128, in run_measurements
    dataset_subset = subset_for_test(dataset_subset)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/utils.py", line 17, in subset_for_test
    subset = pd.concat(subsets, axis=0)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 228, in concat
    copy=copy, sort=sort)
  File "/anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by sameeravithana** [comment]
I also have the same issue when running measurements other than `multi-platform`.
`SOCIALSIM TASKRUNNER   | Subsetting population data... 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/conda/anaconda3/envs/pnnl_socialsim/lib/python3.6/site-packages/socialsim/run.py", line 128, in run_measurements
    dataset_subset = subset_for_test(dataset_subset)
  File "/usr/local/conda/anaconda3/envs/pnnl_socialsim/lib/python3.6/site-packages/socialsim/utils.py", line 17, in subset_for_test
    subset = pd.concat(subsets, axis=0)
  File "/usr/local/conda/anaconda3/envs/pnnl_socialsim/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 228, in concat
    copy=copy, sort=sort)
  File "/usr/local/conda/anaconda3/envs/pnnl_socialsim/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate`

**Comment by emily-grace** [comment]
This was caused when the code tried to subset on platforms that weren't present in the simulation.  We've updated the error handling for this.

FYI....this error occurred in the "subset_for_test" function which limits the data size to only 1000 events and is meant for testing the code on a small dataset.  To avoid this, you should instantiate the TaskRunner with test=False.
